export function saveToStorage(key, data) {
  try {
    localStorage.setItem(key, JSON.stringify(data));
    return true;
  } catch (e) {
    console.error('Storage save error:', e);
    return false;
  }
}

export function loadFromStorage(key, fallback = null) {
  try {
    const item = localStorage.getItem(key);
    return item ? JSON.parse(item) : fallback;
  } catch (e) {
    console.error('Storage load error:', e);
    return fallback;
  }
}

export function removeFromStorage(key) {
  try {
    localStorage.removeItem(key);
    return true;
  } catch (e) {
    return false;
  }
}

export function generateReport(project) {
  const lines = [];
  lines.push('QS CALCULATOR — PROJECT REPORT');
  lines.push('='.repeat(50));
  lines.push(`Project: ${project.name}`);
  lines.push(`Type: ${project.type}`);
  lines.push(`Date: ${new Date(project.date).toLocaleDateString('en-GB')}`);
  lines.push(`Unit System: ${project.unit === 'imperial' ? 'Imperial' : 'Metric'}`);
  lines.push('');
  lines.push('INPUTS:');
  lines.push('-'.repeat(30));
  if (project.inputs) {
    Object.entries(project.inputs).forEach(([k, v]) => {
      lines.push(`  ${k}: ${v}`);
    });
  }
  lines.push('');
  lines.push('RESULTS:');
  lines.push('-'.repeat(30));
  if (project.results) {
    Object.entries(project.results).forEach(([k, v]) => {
      if (typeof v !== 'object') {
        lines.push(`  ${k}: ${v}`);
      }
    });
  }
  lines.push('');
  lines.push('─'.repeat(50));
  lines.push('Generated by QS Calculator v2.1.0');
  lines.push(`Report generated: ${new Date().toLocaleString('en-GB')}`);
  return lines.join('\n');
}

export function exportCSV(data, filename = 'qs-export.csv') {
  if (!data || !data.length) return;
  const headers = Object.keys(data[0]);
  const rows = data.map(row =>
    headers.map(h => {
      const val = row[h] ?? '';
      return typeof val === 'string' && val.includes(',') ? `"${val}"` : val;
    }).join(',')
  );
  const csv = [headers.join(','), ...rows].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadTextReport(project) {
  const text = generateReport(project);
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${project.name || 'report'}-qs-report.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
